![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on! 

In [1]:
import numpy as np

## Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[1::2]

array([2, 4])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int32')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [18]:
np.array([-91, 2, 3, 4], dtype=np.uint8)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15600\2838442821.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -91 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  np.array([-91, 2, 3, 4], dtype=np.uint8)


array([165,   2,   3,   4], dtype=uint8)

In [19]:
256 **3

16777216

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
import sys
d = np.array([{'a': 1}, sys])

In [23]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensions and shapes

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [25]:
A.shape

(2, 3)

In [26]:
A.ndim

2

In [27]:
A.size

6

In [28]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [29]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [30]:
B.shape

(2, 2, 3)

In [31]:
B.ndim

3

In [32]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [40]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [38]:
C.dtype

dtype('int32')

In [39]:
C.shape

(2, 2, 3)

In [44]:
C.size

2

In [45]:
type(C[0])

list

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexing and Slicing of Matrices

In [41]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [42]:
A.shape

(3, 3)

In [43]:
A[:,0]

array([1, 4, 7])

In [44]:
A[1][0]

4

In [52]:
# A[d1, d2, d3, d4]

In [45]:
A[1, 0]

4

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [49]:
A[:2, 2:]

array([[3],
       [6]])

In [50]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
A[1] = [10,]

In [52]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [53]:
A[2] = 99

In [54]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Summary statistics

In [55]:
a = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [56]:
a.shape

(2, 2, 3)

In [58]:
a.choose()

TypeError: choose() takes exactly 1 argument (0 given)

In [70]:
a.mean()

5.0

In [82]:
a.std()

3.452052529534663

In [83]:
a.var()

11.916666666666666

In [84]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.sum()

In [ ]:
A.mean()

In [ ]:
A.std()

In [ ]:
A.sum(axis=0)

In [ ]:
A.sum(axis=1)

In [ ]:
A.mean(axis=0)

In [ ]:
A.mean(axis=1)

In [ ]:
A.std(axis=0)

In [ ]:
A.std(axis=1)

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Broadcasting and Vectorized operations

In [86]:
a = np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a + 10

array([10, 11, 12, 13])

In [89]:
a * 10

array([ 0, 10, 20, 30])

In [90]:
a

array([0, 1, 2, 3])

In [91]:
a += 100

In [92]:
a

array([100, 101, 102, 103])

In [93]:
l = [0, 1, 2, 3]

In [94]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [95]:
a = np.arange(4)

In [96]:
a

array([0, 1, 2, 3])

In [97]:
b = np.array([10, 10, 10, 10])

In [99]:
b,a

(array([10, 10, 10, 10]), array([0, 1, 2, 3]))

In [100]:
a + b

array([10, 11, 12, 13])

In [101]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Boolean arrays
_(Also called masks)_

In [102]:
a = np.arange(4)

In [103]:
a

array([0, 1, 2, 3])

In [104]:
a[0], a[-1]

(0, 3)

In [105]:
a[[0, -1]]

array([0, 3])

In [106]:
a[[True, False, False, True]]

array([0, 3])

In [107]:
a

array([0, 1, 2, 3])

In [109]:
np.where(a >= 2)

(array([2, 3], dtype=int64),)

In [110]:
a[a >= 2]

array([2, 3])

In [111]:
a.mean()

1.5

In [112]:
a[a > a.mean()]

array([2, 3])

In [113]:
a[~(a > a.mean())]

array([0, 1])

In [114]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [115]:
a[(a <= 2) and (a % 2 == 0)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [116]:
A = np.random.randint(100, size=(3, 3))

In [117]:
A

array([[98, 62, 81],
       [82, 99, 90],
       [43, 54, 71]])

In [118]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([98, 81, 99, 43, 71])

In [119]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [120]:
A[A > 30]

array([98, 62, 81, 82, 99, 90, 43, 54, 71])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Linear Algebra

In [121]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [122]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [123]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [125]:
(A @ B).shape

(3, 2)

In [127]:
B.T.shape

(2, 3)

In [128]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Size of objects in Memory

### Int, floats

In [132]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [133]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [134]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [135]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [136]:
np.dtype(float).itemsize

8

### Lists are even larger

In [137]:
# A one-element list
sys.getsizeof([1])

64

In [138]:
# An array of one element in numpy
np.array([1]).nbytes

4

### And performance is also important

In [139]:
l = list(range(100000))

In [140]:
a = np.arange(100000)

In [141]:
%time np.sum(a ** 2)

Wall time: 0 ns


216474736

In [142]:
%time sum([x ** 2 for x in l])

Wall time: 48 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Useful Numpy functions

### `random` 

In [143]:
np.random.random(size=2)

array([0.52560223, 0.06111283])

In [144]:
np.random.normal(size=2)

array([-0.32526739, -0.59571883])

In [145]:
np.random.rand(2, 4)

array([[0.99864156, 0.98473318, 0.63523069, 0.8297298 ],
       [0.3981446 , 0.34920352, 0.51996721, 0.65111128]])

---
### `arange`

In [146]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [148]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [149]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [150]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [151]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [152]:


np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [153]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---
### `zeros`, `ones`, `empty`

In [154]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [155]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [157]:
np.zeros((3, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [158]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [159]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [160]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [161]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---
### `identity` and `eye`

In [162]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [163]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [164]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [165]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [166]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [167]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)